name: Test and Deploy

on:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: Install dependencies
      run: npm ci
    - name: Test
      run: npm test

  frontend-test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm run install:frontend
    - run: npm run test:frontend:unit

  functions-test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm run install:functions
    - run: npm run test:functions

  deploy:
    runs-on: ubuntu-latest
    needs: [frontend-test, functions-test]
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: Build and Deploy
      run: |
        npm run build:functions
        npm run build:frontend
        firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}